In [1]:
import pandas as pd 
import psycopg2
from sqlalchemy import create_engine
df=pd.read_csv('customer_shopping_behavior.csv')

In [2]:
df.head()

  Customer ID\tAge\tGender\tItem Purchased\tCategory\tPurchase Amount (USD)\tLocation\tSize\tColor\tSeason\tReview Rating\tSubscription Status\tShipping Type\tDiscount Applied\tPromo Code Used\tPrevious Purchases\tPayment Method\tFrequency of Purchases
0  1\t55\tMale\tBlouse\tClothing\t53\tKentucky\tL...
1  2\t19\tMale\tSweater\tClothing\t64\tMaine\tL\t...
2  3\t50\tMale\tJeans\tClothing\t73\tMassachusett...
3  4\t21\tMale\tSandals\tFootwear\t90\tRhode Isla...
4  5\t45\tMale\tBlouse\tClothing\t49\tOregon\tM\t...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                     --------------  -----
 0   Customer ID	Age	Gender	Item Purchased	Category	Purchase Amount (USD)	Location	Size	Color	Season	Review Rating	Subscription Status	Shipping Type	Discount Applied	Promo Code Used	Previous Purchases	Payment Method	Frequency of Purchases  3900 non-null   object
dtypes: object(1)
memory usage: 30.6+ KB

In [4]:
df.describe()

       Customer ID\tAge\tGender\tItem Purchased\tCategory\tPurchase Amount (USD)\tLocation\tSize\tColor\tSeason\tReview Rating\tSubscription Status\tShipping Type\tDiscount Applied\tPromo Code Used\tPrevious Purchases\tPayment Method\tFrequency of Purchases
count                                                3900
unique                                               3900
top     1\t55\tMale\tBlouse\tClothing\t53\tKentucky\tL...
freq                                                    1

In [5]:
df.describe(include='all')

       Customer ID\tAge\tGender\tItem Purchased\tCategory\tPurchase Amount (USD)\tLocation\tSize\tColor\tSeason\tReview Rating\tSubscription Status\tShipping Type\tDiscount Applied\tPromo Code Used\tPrevious Purchases\tPayment Method\tFrequency of Purchases
count                                                3900
unique                                               3900
top     1\t55\tMale\tBlouse\tClothing\t53\tKentucky\tL...
freq                                                    1

In [6]:
df.isnull().sum()

Customer ID\tAge\tGender\tItem Purchased\tCategory\tPurchase Amount (USD)\tLocation\tSize\tColor\tSeason\tReview Rating\tSubscription Status\tShipping Type\tDiscount Applied\tPromo Code Used\tPrevious Purchases\tPayment Method\tFrequency of Purchases    0
dtype: int64

In [7]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

KeyError: 'Category'

In [ ]:
df.isnull().sum()

In [12]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [13]:
df.head()

  customer_id\tage\tgender\titem_purchased\tcategory\tpurchase_amount_(usd)\tlocation\tsize\tcolor\tseason\treview_rating\tsubscription_status\tshipping_type\tdiscount_applied\tpromo_code_used\tprevious_purchases\tpayment_method\tfrequency_of_purchases
0  1\t55\tMale\tBlouse\tClothing\t53\tKentucky\tL...
1  2\t19\tMale\tSweater\tClothing\t64\tMaine\tL\t...
2  3\t50\tMale\tJeans\tClothing\t73\tMassachusett...
3  4\t21\tMale\tSandals\tFootwear\t90\tRhode Isla...
4  5\t45\tMale\tBlouse\tClothing\t49\tOregon\tM\t...

In [9]:
df.columns

Index(['Customer ID\tAge\tGender\tItem Purchased\tCategory\tPurchase Amount (USD)\tLocation\tSize\tColor\tSeason\tReview Rating\tSubscription Status\tShipping Type\tDiscount Applied\tPromo Code Used\tPrevious Purchases\tPayment Method\tFrequency of Purchases'], dtype='object')

In [10]:
df.columns

Index(['Customer ID\tAge\tGender\tItem Purchased\tCategory\tPurchase Amount (USD)\tLocation\tSize\tColor\tSeason\tReview Rating\tSubscription Status\tShipping Type\tDiscount Applied\tPromo Code Used\tPrevious Purchases\tPayment Method\tFrequency of Purchases'], dtype='object')

In [ ]:
#create a column age_group
labels=['Young Adult','Adult','Middle-Aged','Senior']
df['age_group']=pd.qcut(df['age'], q=4, labels = labels)

In [ ]:
df[['age','age_group']].head(20)

In [ ]:
#create column purchase frequency days
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 months':90,
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [ ]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

In [ ]:
(df['discount_applied']==df['promo_code_used']).all()

In [ ]:
df=df.drop('promo_code_used',axis=1)

In [ ]:
df.columns

In [ ]:
pip install psycopg2-binary sqlalchemy

In [8]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')
from sqlalchemy import create_engine

username = "postgres"
password = "Simran%4004"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data Successfully loaded into table '{table_name}' in database '{database}',")

Data Successfully loaded into table 'customer' in database 'customer_behavior',

In [16]:
import pandas as pd
from sqlalchemy import create_engine

df=pd.read_csv('customer_shopping_behavior.csv',sep="\t")
print(df.head())
print(df.columns)

username = "postgres"
password = "Simran%4004"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data Successfully loaded into table '{table_name}' in database '{database}',")

   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   Shipping Type Discount Applied Promo Code Used  Previous Purchases  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3   Next Day Air              Yes             Yes                  49
4  Free Shipping              Yes             Yes                  31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually
Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')
Data Successfully loaded into table 'customer' in database 'customer_behavior',